import validEmail from './validEmail';
import validPassword from './validPassword';
import validName from './validName'
import { charactersAnalyze, toggleIsChangeFormElements } from './configEndpointsAnayze'
import accessLocalStorage from './accessLocalStorage';
import {
  clickToCall,
  cancelClickToCall,
  trasferCall,
  cancelTrasferCall,
  clickToSpy,
  requestToken,
  registerUser,
  fetchEndpoints,
  fetchCallsDataBase,
  fetchCallsAnalistas,
  fetchRecCall,
  fetchCallOnDay,
  fetchDataReport,
  fetchSectors,
  fetchDataReportList,
  fetchRowsChartSectors,
  exportReportGenerate,
  exportReportDownload,
  exportReportGenerateLogs,
  exportCreateTrunks,
  exportSelectAllTrunks,
  exportDeleteTrunks,
  exportCreateEndpoints,
  exportSelectAllEndpoints,
  exportSelectEndpointsById,
  exportUpdateEndpoints,
  exportDeleteEndpoints,
  exportCreateQueues,
  exportSelectAllQueues,
  exportSelectQueuesByName,
  exportUpdateQueues,
  exportDeleteQueues,
  exportCreateQueueMembers,
  exportSelectAllQueueMembers,
  exportSelectQueueMemberByName,
  exportSelectQueueMemberByEndpoint,
  exportDeleteQueueMember,
  exportCreateMoh,
  exportSelectAllMohs,
  exportDeleteMohs,
} from './api';

export {
  validEmail,
  validPassword,
  validName,
  charactersAnalyze,
  toggleIsChangeFormElements,
  accessLocalStorage,
  clickToCall,
  cancelClickToCall,
  trasferCall,
  cancelTrasferCall,
  requestToken,
  registerUser,
  fetchEndpoints,
  fetchCallsDataBase,
  fetchCallsAnalistas,
  fetchRecCall,
  fetchCallOnDay,
  clickToSpy,
  fetchDataReport,
  fetchSectors,
  fetchDataReportList,
  fetchRowsChartSectors,
  exportReportGenerate,
  exportReportDownload,
  exportReportGenerateLogs,
  exportCreateTrunks,
  exportSelectAllTrunks,
  exportDeleteTrunks,
  exportCreateEndpoints,
  exportSelectAllEndpoints,
  exportSelectEndpointsById,
  exportUpdateEndpoints,
  exportDeleteEndpoints,
  exportCreateQueues,
  exportSelectAllQueues,
  exportSelectQueuesByName,
  exportUpdateQueues,
  exportDeleteQueues,
  exportCreateQueueMembers,
  exportSelectAllQueueMembers,
  exportSelectQueueMemberByName,
  exportSelectQueueMemberByEndpoint,
  exportDeleteQueueMember,
  exportCreateMoh,
  exportSelectAllMohs,
  exportDeleteMohs,
 } 
